Fix: Handling errors when an item is not found in an HTML string
the following error occurred:

2025-02-09 01:55:08,776 - __main__ - ERROR - list index out of range
Traceback (most recent call last):
  File "xyPageScraper.py", line 58, in <module>
  File "pageScraper.py", line 80, in downloadPics
  File "fengniaoPageScraper.py", line 21, in getPicList
IndexError: list index out of range

to handle this:
1, add a exception class: ItemsNotFoundError
2, when an item is not found in an HTML string, raise the exception
3, catch and handle the exception in main module

 Changes to be committed:
	modified:   fengniaoPageScraper.py
	modified:   locales/zh_CN/LC_MESSAGES/xyPageScraper.po
	modified:   pageScraper.py
	modified:   pconlinePageScraper.py
	modified:   xyPageScraper.py